apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
      - name: newapp
        image: shumet/newapp:1.1.2
        ports:
        - containerPort: 5002
        imagePullPolicy: Always  # ensure fresh pull on every sync
---
apiVersion: v1
kind: Service
metadata:
  name: newapp
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  selector:
    app: newapp
